/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hw.h"

bool_t
xdr_param (XDR *xdrs, param *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_param2 (XDR *xdrs, param2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nick, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->content, 1048576,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_param3 (XDR *xdrs, param3 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->cont_client_side))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nick_client_side, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_return1 (XDR *xdrs, return1 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->campo_vali))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->content, 1048576,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
