# GNU Makefile
JAVAC = javac

JFLAGS = -g
.SUFFIXES: .java .class
.java.class:
	$(JAVAC) $(JFLAGS) $*.java

CLASSES = \
	ChatServer.java\
	ChatClient.java\
	ChatServerInterface.java

default: classes

classes: $(CLASSES:.java=.class)

clean:
	rm -f *.class;
